### ISSUE TITLE
spoon.txt hates me

### ISSUE THREAD

**Issue by XElectricX** [Matthww/PlayerInfo#1]
Ok, so, trying to agree to the terms but it does not recognize my "yes". I have put it after the question mark, after the question mark with no spaces, after the question mark with an indentation, with 2 indentations, with indentations and spaces, etc... Any way I put it, the plugin disables itself because it thinks I did not type in "yes". 😞

**Comment by Matthww** [comment]
@XElectricX Let's just start of with what server software you are using.

**Comment by XElectricX** [comment]
/version: `Tesseract 1.3.0-Dev 「Unity」 implementing API version 3.0.0-ALPHA6 for Minecraft: PE v1.1.0.55 (protocol version 113)`

**Comment by Matthww** [comment]
I don't think the plugin will work at all even if I'll remove the spoon detector

**Comment by XElectricX** [comment]
Oh, how come?

**Comment by Matthww** [comment]
The differences between the API is too big
