### ISSUE TITLE
Namespace Error

### ISSUE THREAD

**Issue by MonoAdrian23** [Matthww/PlayerInfo#13]
When i try to check a Namespaced Profile i become an Internal Server Error
Pocketmine Latest
Playerinfo Latest
21:53:36] [Server thread/CRITICAL]: ErrorException: "Undefined index: Deniz_Ahu" (EXCEPTION) in "plugins/PlayerInfo (1).phar/src/Matthww/PlayerInfo/PlayerInfo" at line 110

**Comment by Matthww** [comment]
What version are you currently using?

**Comment by MonoAdrian23** [comment]
V.2.1.3

**Comment by Matthww** [comment]
Small question is the user "Deniz_Ahu" you and is that person online?

**Comment by MonoAdrian23** [comment]
No the User is another one.
Player is online.
It works perfectly but Namespaced Players Error
Sorry for my english

**Comment by MonoAdrian23** [comment]
The _ is in the name because I use the plugin NameSpaceRemover

**Comment by Matthww** [comment]
Could you try and remove the NameSpaceRemover plugin and see if you still get errors?
