### ISSUE TITLE
update

### ISSUE THREAD

**Issue by TDMidkwhatisxd** [Matthww/PlayerInfo#7]
3.0.0

**Comment by XuPaperCup** [comment]
https://poggit.pmmp.io/r/35071/PlayerInfo_pr-3.phar

**Comment by XuPaperCup** [comment]
Ok

**Comment by Matthww** [comment]
This is the updated version for PMMP 3.0.0-3.0.4
https://poggit.pmmp.io/r/35623/PlayerInfo_dev-27.phar
